# Data Formats
Here we will larn how to handle data formats like lists, vectors, matrices, arrays, data frames ecc. In R is important to change certain data formats into others

In [49]:
n1 <- 15 #double precision by default
n1
typeof(n1)

[1] 15

[1] "double"

In [50]:
n2 <- 1.5 #double precision by default
n2
typeof(n2)

[1] 1.5

[1] "double"

In [51]:
c1 <- 'c'
c1
typeof(c1)

[1] "c"

[1] "character"

In [52]:
c2 <- 'Hello World'
c2
typeof(c2)

[1] "Hello World"

[1] "character"

In [53]:
l1 <- TRUE
typeof(l1)

[1] "logical"

In [54]:
v1 <- c(1,2,3,4,5) #c = concatenate
v1
is.vector(v1) #is it a vector?

[1] 1 2 3 4 5

[1] TRUE

## Matrix

In [55]:
m1 <- matrix(c(T,T,F,T,F,T), nrow=2) #defining matrix
m1

tmp <- c(T,T,F,T,F,T) #matrix with variable
m2 <- matrix(tmp, nrow=2)
m2

[,1] [,2]  [,3] 
[1,] TRUE FALSE FALSE
[2,] TRUE  TRUE  TRUE

[,1] [,2]  [,3] 
[1,] TRUE FALSE FALSE
[2,] TRUE  TRUE  TRUE

In [56]:
tmp <- c('a', 'b', 
         'c', 'd')
m3 <- matrix(tmp, 
             nrow=2, 
             byrow = T)
m3

[,1] [,2]
[1,] a    b   
[2,] c    d

In [57]:
#give data, then dimensions (rows, columns, tables)=c(4,3,2)
a1 <- array( c(1:24), c(4,3,2))
print(a1)

#use print(a1) instead of a1 

, , 1

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12

, , 2

     [,1] [,2] [,3]
[1,]   13   17   21
[2,]   14   18   22
[3,]   15   19   23
[4,]   16   20   24



Combining differents object types will result in a data frame of only strings. To avoid this use the function as.data.frame (make it a data frame)

In [58]:
vNumeric <- c(1,2,3)
vCharacter <- c('a','b','c')
vLogical <- c(T, F, T)

dfa <- cbind(vNumeric, vCharacter, vLogical)
print(dfa)

df <- as.data.frame(cbind(vNumeric, vCharacter, vLogical))
df

     vNumeric vCharacter vLogical
[1,] "1"      "a"        "TRUE"  
[2,] "2"      "b"        "FALSE" 
[3,] "3"      "c"        "TRUE"  


vNumeric vCharacter vLogical
1 1        a          TRUE    
2 2        b          FALSE   
3 3        c          TRUE

### Coercing Typos
We can either make a list combining three different object typos. In general when we 'coerce' different types it will automatically convert them into strings

In [59]:
list1 <- list(vNumeric, vCharacter, vLogical)
list1

#or concatenate list
list2 <- list(vNumeric, vCharacter, vLogical, list1)
print(list2)

[[1]]
[1] 1 2 3

[[2]]
[1] "a" "b" "c"

[[3]]
[1]  TRUE FALSE  TRUE

[[1]]
[1] 1 2 3

[[2]]
[1] "a" "b" "c"

[[3]]
[1]  TRUE FALSE  TRUE

[[4]]
[[4]][[1]]
[1] 1 2 3

[[4]][[2]]
[1] "a" "b" "c"

[[4]][[3]]
[1]  TRUE FALSE  TRUE




In [60]:
coerce1 <- c(1, 'b', TRUE)
typeof(coerce1)

#or specifically
coerce2 <- 5
typeof(coerce2)

#if we want String ---> Int
coerce3 <- as.numeric( c('1','2','3'))
typeof(coerce3)

[1] "character"

[1] "double"

[1] "double"

In [61]:
#with Matrices
(coerce6 <- matrix(1:9, nrow=3))
is.matrix(coerce6) #is it a matrix?

(coerce7 <- as.data.frame(matrix(1:9, nrow=3)))
is.data.frame(coerce7)

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

[1] TRUE

V1 V2 V3
1 1  4  7 
2 2  5  8 
3 3  6  9

[1] TRUE

# Factors

In [63]:
#create data
(x1 <- 1:3)
(y  <- 1:9)

#combine data
(df1 <- cbind.data.frame(x1,y))
typeof(df1$x1)
str(df1) #structure of df1

[1] 1 2 3

[1] 1 2 3 4 5 6 7 8 9

x1 y
1 1  1
2 2  2
3 3  3
4 1  4
5 2  5
6 3  6
7 1  7
8 2  8
9 3  9

[1] "integer"

'data.frame':	9 obs. of  2 variables:
 $ x1: int  1 2 3 1 2 3 1 2 3
 $ y : int  1 2 3 4 5 6 7 8 9


In [70]:
x3 <- c(1:3)
df3 <- cbind.data.frame(x3,y)
df3$x3 <- factor(df3$x3,
                 levels = c(1,2,3),
                 labels = c('macOS', 'Windows', 'Linux'))
typeof(df3$y)
str(df3)
df3

[1] "integer"

'data.frame':	9 obs. of  2 variables:
 $ x3: Factor w/ 3 levels "macOS","Windows",..: 1 2 3 1 2 3 1 2 3
 $ y : int  1 2 3 4 5 6 7 8 9


x3      y
1 macOS   1
2 Windows 2
3 Linux   3
4 macOS   4
5 Windows 5
6 Linux   6
7 macOS   7
8 Windows 8
9 Linux   9